### ISSUE TITLE
번역 오류 하나 보고 가능한가요?

### ISSUE THREAD

**Issue by DaDazirul** [hyuckkim/vp_kr#17]
![20240208173137_1](https://github.com/hyuckkim/vp_kr/assets/159424425/070792eb-f59c-4231-9759-d952cffd501e)

타지마할 설명이 치첸이트사와 겹쳐서 보고 드립니다.

**Comment by hyuckkim** [comment]
수정했습니다! exe 파일을 새로 받아주세요.
제보해주셔서 감사합니다!
